# Generated by Django 5.2.3 on 2025-06-26 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('nama_aktivitas', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lingkungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('tanggal_diperbarui', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LogAktivitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('aktivitas', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('no', models.CharField(blank=True, max_length=20, null=True)),
                ('dokumentasi', models.URLField(blank=True, null=True)),
                ('laporan', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemImplementation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('nama_model', models.CharField(default='default_model', max_length=100)),
                ('status_project', models.CharField(max_length=50)),
                ('dokumentasi_model', models.URLField(help_text='Link ke Google Colab')),
                ('laporan_model', models.FileField(blank=True, help_text='Upload PDF laporan model', null=True, upload_to='laporan/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_transaksi', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('waktu', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransaksiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_transaksi', models.DateTimeField(auto_now_add=True)),
                ('nama_model', models.CharField(max_length=200)),
                ('input_data', models.TextField()),
                ('output_data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Catatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(auto_now_add=True)),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('teknisi', models.CharField(max_length=255)),
                ('model_terkait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.systemimplementation')),
            ],
        ),
        migrations.CreateModel(
            name='ValidasiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validator', models.CharField(max_length=100)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('status_validasi', models.CharField(choices=[('Valid', 'Valid'), ('Perlu Revisi', 'Perlu Revisi')], max_length=50)),
                ('tanggal_validasi', models.DateTimeField(auto_now_add=True)),
                ('model_terkait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.systemimplementation')),
            ],
        ),
        migrations.CreateModel(
            name='HasilUjiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hasil_perhitungan', models.TextField()),
                ('rekomendasi', models.TextField()),
                ('kirim_ke_pm', models.BooleanField(default=False)),
                ('tanggal_uji', models.DateTimeField(auto_now_add=True)),
                ('model_terkait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.validasimodel')),
            ],
        ),
    ]
