# Generated by Django 5.2.1 on 2025-06-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logaktivitas',
            name='dokumentasi',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logaktivitas',
            name='laporan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='logaktivitas',
            name='no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='logaktivitas',
            name='person',
            field=models.CharField(default='Sistem', max_length=100),
            preserve_default=False,
        ),
    ]
