# Generated by Django 5.2.1 on 2025-06-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemimplementation',
            name='input_model',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemimplementation',
            name='output_model',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aktivitas',
            name='status',
            field=models.CharField(choices=[('Hijau', 'Hijau'), ('Oranye', 'Oranye'), ('Merah', 'Merah')], max_length=50),
        ),
    ]
