# Generated by Django 5.2.1 on 2025-06-21 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_logaktivitas_dokumentasi_logaktivitas_laporan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logaktivitas',
            name='person',
        ),
    ]
