# Generated by Django 5.2.1 on 2025-06-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_systemimplementation_input_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaKelompok', models.TextField()),
                ('deskripsi', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
    ]
