# Generated by Django 5.2.3 on 2025-06-21 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_logaktivitas_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemImplementation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('nama_model', models.CharField(default='default_model', max_length=100)),
                ('status_project', models.CharField(max_length=50)),
                ('dokumentasi_model', models.URLField(help_text='Link ke Google Colab')),
                ('laporan_model', models.FileField(blank=True, help_text='Upload PDF laporan model', null=True, upload_to='laporan/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
