# Generated by Django 5.2.1 on 2025-06-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementsSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaKelompok', models.TextField()),
                ('deskripsi', models.TextField()),
                ('status', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Management',
        ),
    ]
