# Generated by Django 5.2.1 on 2025-06-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_managementssi_delete_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemimplementation',
            name='dokumentasi_model_file',
            field=models.FileField(blank=True, null=True, upload_to='dokumen/'),
        ),
    ]
