# Generated by Django 5.2.3 on 2025-06-24 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_systemimplementation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidasiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validator', models.CharField(max_length=100)),
                ('catatan', models.TextField(blank=True, null=True)),
                ('status_validasi', models.CharField(choices=[('Valid', 'Valid'), ('Perlu Revisi', 'Perlu Revisi')], max_length=50)),
                ('tanggal_validasi', models.DateTimeField(auto_now_add=True)),
                ('model_terkait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.systemimplementation')),
            ],
        ),
    ]
