# Generated by Django 5.2.1 on 2025-06-29 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_systemimplementation_dokumentasi_model_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemimplementation',
            name='dokumentasi_model_file',
        ),
    ]
