# Generated by Django 5.2.1 on 2025-06-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_systemimplementation_dokumentasi_model_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemimplementation',
            name='dokumentasi_model',
            field=models.URLField(blank=True, help_text='Link ke dokumentasi model', null=True),
        ),
    ]
