# Generated by Django 5.2.1 on 2025-06-29 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_systemimplementation_dokumentasi_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='lingkungan',
            name='model_terkait',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.systemimplementation'),
        ),
    ]
