# Generated by Django 5.2.1 on 2025-06-29 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_lingkungan_model_terkait'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemimplementation',
            name='sumber',
            field=models.CharField(default='SI', max_length=50),
        ),
    ]
